name: Build APK

on:
workflow_dispatch: # Isse aap jab chahein button daba kar APK bana sakte hain

jobs:
build:
runs-on: ubuntu-latest

steps:
- name: Checkout code
uses: actions/checkout@v4

- name: Buildozer Action
uses: ArtemSBulgakov/buildozer-action@v1
with:
workdir: .
buildozer_version: master

- name: Upload APK Artifact
uses: actions/upload-artifact@v4
with:
name: Billet-Scanner-APK
path: bin/*.apk
